---
- name: Copy file from local host to remote clients
  hosts: all

  tasks:
  - name: Copying file
    become: true
    copy:
      src: /home/kslavkov7/some.cfg
      dest: /tmp
      owner: kslavkov7
      group: kslavkov7
      mode: 0644   
