---
- name: Install apache webserver
  hosts: localhost

  tasks:
    - name: Install apache on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Ubuntu" 
    
    - name: Install apache on CentOS
      yum: 
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"


